# Auto-generated MASTER LOOKUP TABLE for RITC 2026 Merger Arbitrage
# Generated from 1934 observations
# across 255 unique headlines

MASTER_LOOKUP = {
    'BONDHOLDER LITIGATION RESOLVED': {
        "direction": "positive",
        "severity": "large",
        "category": "FIN",
        "avg_dp": 0.15322,
        "avg_price_move": 8.225,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Bondholder Litigation Resolved
    },
    'BROAD MARKET SELL-OFF AS RISK SENTIMENT DETERIORATES': {
        "direction": "negative",
        "severity": "large",
        "category": "FIN",
        "avg_dp": -0.1487,
        "avg_price_move": -0.457,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: Broad Market Sell-Off as Risk Sentiment Deteriorates
    },
    'FINAL CLOSING CONDITIONS CHECKLIST PUBLISHED': {
        "direction": "negative",
        "severity": "large",
        "category": "FIN",
        "avg_dp": -0.10324,
        "avg_price_move": -0.128,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: Final Closing Conditions Checklist Published
    },
    'SENATE COMMITTEE LAUNCHES INQUIRY INTO INDUSTRY CONSOLIDATION': {
        "direction": "positive",
        "severity": "large",
        "category": "FIN",
        "avg_dp": 0.09362,
        "avg_price_move": 1.653,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: Senate Committee Launches Inquiry Into Industry Consolidatio
    },
    'VOTE TRACKING SHOWS MAJORITY SUPPORT': {
        "direction": "negative",
        "severity": "large",
        "category": "SHR",
        "avg_dp": -0.08473,
        "avg_price_move": -1.192,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 2,
        # example: Vote Tracking Shows Majority Support
    },
    'RATE CASE PROCEEDINGS INITIATED': {
        "direction": "positive",
        "severity": "large",
        "category": "FIN",
        "avg_dp": 0.07988,
        "avg_price_move": 1.128,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 7,
        # example: Rate Case Proceedings Initiated
    },
    'ENVIRONMENTAL GROUPS CHALLENGE MERGER': {
        "direction": "negative",
        "severity": "large",
        "category": "FIN",
        "avg_dp": -0.07539,
        "avg_price_move": -0.426,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: Environmental Groups Challenge Merger
    },
    'MAJOR RATING AGENCY REVISES SECTOR OUTLOOKS DOWNWARD': {
        "direction": "positive",
        "severity": "large",
        "category": "FIN",
        "avg_dp": 0.0635,
        "avg_price_move": 1.093,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: Major Rating Agency Revises Sector Outlooks Downward
    },
    'UK CMA PROVISIONALLY CLEARS DEAL': {
        "direction": "positive",
        "severity": "medium",
        "category": "REG",
        "avg_dp": 0.05429,
        "avg_price_move": 0.951,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 7,
        # example: UK CMA Provisionally Clears Deal
    },
    'TRADE POLICY REVISIONS ANNOUNCED WITH CROSS-SECTOR IMPACT': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.05128,
        "avg_price_move": -1.46,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 2,
        # example: Trade Policy Revisions Announced With Cross-Sector Impact
    },
    'STATE REGULATORS EXPRESS CONCERNS': {
        "direction": "positive",
        "severity": "medium",
        "category": "REG",
        "avg_dp": 0.04799,
        "avg_price_move": 0.183,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: State Regulators Express Concerns
    },
    'POTENTIAL COMPETING INTEREST EMERGES': {
        "direction": "positive",
        "severity": "medium",
        "category": "ALT",
        "avg_dp": 0.04714,
        "avg_price_move": 0.814,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Potential Competing Interest Emerges
    },
    'SETTLEMENT OF SHAREHOLDER LITIGATION': {
        "direction": "positive",
        "severity": "medium",
        "category": "SHR",
        "avg_dp": 0.04583,
        "avg_price_move": 0.79,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: Settlement of Shareholder Litigation
    },
    'OUTSIDE DATE EXTENDED TO YEAR-END': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.0432,
        "avg_price_move": 0.034,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 8,
        # example: Outside Date Extended to Year-End
    },
    'INDUSTRY LOBBYISTS SUPPORT TRANSACTION': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.04283,
        "avg_price_move": -0.026,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 4,
        # example: Industry Lobbyists Support Transaction
    },
    'CONGRESSIONAL HEARING ANNOUNCED': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.04258,
        "avg_price_move": 0.42,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 6,
        # example: Congressional Hearing Announced
    },
    'CLOSING CONDITIONS STATUS': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.0425,
        "avg_price_move": -0.249,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 5,
        # example: Closing Conditions Status
    },
    'ALL-STOCK STRUCTURE ELIMINATES FINANCING': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.04247,
        "avg_price_move": -0.077,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: All-Stock Structure Eliminates Financing
    },
    'STATE UTILITY COMMISSIONS REQUEST HEARINGS': {
        "direction": "positive",
        "severity": "medium",
        "category": "REG",
        "avg_dp": 0.03972,
        "avg_price_move": 0.457,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: State Utility Commissions Request Hearings
    },
    'FERC REVIEW INITIATED FOR ENERGY DEAL': {
        "direction": "positive",
        "severity": "medium",
        "category": "REG",
        "avg_dp": 0.03704,
        "avg_price_move": 1.724,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: FERC Review Initiated for Energy Deal
    },
    'EU COMMISSION REQUESTS DETAILED MARKET SHARE DATA': {
        "direction": "positive",
        "severity": "medium",
        "category": "REG",
        "avg_dp": 0.03698,
        "avg_price_move": 0.686,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 4,
        # example: EU Commission Requests Detailed Market Share Data
    },
    'DEVELOPER RETENTION INCENTIVES': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.0335,
        "avg_price_move": -0.183,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 6,
        # example: Developer Retention Incentives
    },
    'TERMINATION FEE STRUCTURE DISCLOSED': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.03241,
        "avg_price_move": 0.664,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Termination Fee Structure Disclosed
    },
    'STRESS TEST REQUIREMENTS IMPOSED': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.03241,
        "avg_price_move": -0.685,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 6,
        # example: Stress Test Requirements Imposed
    },
    'EXPECTED CLOSING DATE PUSHED BACK': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.03141,
        "avg_price_move": 0.509,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 5,
        # example: Expected Closing Date Pushed Back
    },
    'POLITICAL OPPOSITION EMERGES FROM FOSSIL FUEL-DEPENDENT STATES': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.03117,
        "avg_price_move": 0.162,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Political Opposition Emerges From Fossil Fuel-Dependent Stat
    },
    'MINORITY SHAREHOLDER LITIGATION': {
        "direction": "negative",
        "severity": "medium",
        "category": "SHR",
        "avg_dp": -0.03007,
        "avg_price_move": -0.699,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: Minority Shareholder Litigation
    },
    'PRELIMINARY APPROACH CONFIRMED': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.02996,
        "avg_price_move": -0.459,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Preliminary Approach Confirmed
    },
    'TIMELINE EXTENDED FOR REGULATORY PROCESS': {
        "direction": "negative",
        "severity": "medium",
        "category": "REG",
        "avg_dp": -0.02972,
        "avg_price_move": -0.51,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Timeline Extended for Regulatory Process
    },
    'CLOSING CONDITIONS TRACKER UPDATED': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.02933,
        "avg_price_move": -0.328,
        "confidence": 1.0,
        "n_obs": 14,
        "n_clean": 9,
        # example: Closing Conditions Tracker Updated
    },
    'POLITICAL OPPOSITION VOICED': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.02926,
        "avg_price_move": 0.906,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: Political Opposition Voiced
    },
    'CONGRESSIONAL BANKING COMMITTEE INQUIRY': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.02923,
        "avg_price_move": -0.144,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 5,
        # example: Congressional Banking Committee Inquiry
    },
    'MIXED ECONOMIC DATA CREATES CROSS-CURRENTS FOR DEAL MARKETS': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.02882,
        "avg_price_move": -0.076,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 6,
        # example: Mixed Economic Data Creates Cross-Currents for Deal Markets
    },
    'STOCK PRICE CONDITIONS CONFIRMED MET': {
        "direction": "negative",
        "severity": "medium",
        "category": "PRC",
        "avg_dp": -0.0271,
        "avg_price_move": 0.255,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 4,
        # example: Stock Price Conditions Confirmed Met
    },
    'HEDGE FUND ACTIVIST OPPOSES DEAL': {
        "direction": "negative",
        "severity": "medium",
        "category": "SHR",
        "avg_dp": -0.0248,
        "avg_price_move": -0.281,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 7,
        # example: Hedge Fund Activist Opposes Deal
    },
    'BRANCH MANAGER RETENTION PROGRAM': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.02365,
        "avg_price_move": 0.418,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: Branch Manager Retention Program
    },
    'OCC RAISES OPERATIONAL RISK CONCERNS': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.02337,
        "avg_price_move": 0.235,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: OCC Raises Operational Risk Concerns
    },
    'EUROPEAN COMMISSION OPENS PHASE II INVESTIGATION': {
        "direction": "positive",
        "severity": "medium",
        "category": "REG",
        "avg_dp": 0.02263,
        "avg_price_move": 0.439,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 5,
        # example: European Commission Opens Phase II Investigation
    },
    'UTILITY COMPANY INTEREST REPORTED': {
        "direction": "positive",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": 0.02236,
        "avg_price_move": 0.009,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: Utility Company Interest Reported
    },
    'TIMELINE ADJUSTMENT': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.0216,
        "avg_price_move": -0.329,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 2,
        # example: Timeline Adjustment
    },
    'EQUITY MARKETS RALLY ON IMPROVED RISK APPETITE': {
        "direction": "negative",
        "severity": "medium",
        "category": "FIN",
        "avg_dp": -0.02154,
        "avg_price_move": -0.352,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 5,
        # example: Equity Markets Rally on Improved Risk Appetite
    },
    'COMPANY SHAREHOLDER CONCERNS': {
        "direction": "positive",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.01986,
        "avg_price_move": 0.304,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Atlas Shareholder Concerns
    },
    'DOJ ANTITRUST CLEARANCE GRANTED': {
        "direction": "negative",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.01959,
        "avg_price_move": -0.622,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: DOJ Antitrust Clearance Granted
    },
    'SHAREHOLDER DERIVATIVE SUIT FILED': {
        "direction": "positive",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.01931,
        "avg_price_move": 0.297,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: Shareholder Derivative Suit Filed
    },
    'ISS ISSUES QUALIFIED SUPPORT': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.019,
        "avg_price_move": -0.424,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: ISS Issues Qualified Support
    },
    'INVESTMENT GRADE BOND OFFERING COMPLETED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01865,
        "avg_price_move": 0.114,
        "confidence": 1.0,
        "n_obs": 11,
        "n_clean": 8,
        # example: Investment Grade Bond Offering Completed
    },
    'EARLY INDICATIONS POINT TO STRONG SHAREHOLDER SUPPORT': {
        "direction": "negative",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.01839,
        "avg_price_move": -0.375,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Early Indications Point to Strong Shareholder Support
    },
    'PERMANENT FINANCING SYNDICATION SUCCESSFUL': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01835,
        "avg_price_move": -0.011,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 9,
        # example: Permanent Financing Syndication Successful
    },
    'CLOSING TIMELINE EXTENDED': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01831,
        "avg_price_move": -0.3,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: Closing Timeline Extended
    },
    'TERMINATION FEE SET AT $240M': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01789,
        "avg_price_move": 0.787,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: Termination Fee Set at $240M
    },
    'COLLAR MECHANISM SPECULATION': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01733,
        "avg_price_move": 0.034,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 2,
        # example: Collar Mechanism Speculation
    },
    'FTC CLEARS TRANSACTION - EARLY TERMINATION': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01679,
        "avg_price_move": -0.137,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: FTC Clears Transaction - Early Termination
    },
    'BANK SECRECY ACT COMPLIANCE REVIEW': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01678,
        "avg_price_move": 0.257,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Bank Secrecy Act Compliance Review
    },
    'COMPETING BANK IDENTIFIED': {
        "direction": "negative",
        "severity": "small",
        "category": "ALT",
        "avg_dp": -0.0161,
        "avg_price_move": -0.247,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 2,
        # example: Competing Bank Identified
    },
    'SYNDICATION ACHIEVES OVERSUBSCRIPTION': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01586,
        "avg_price_move": 0.215,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Syndication Achieves Oversubscription
    },
    'RENEWABLE ENERGY CREDIT TRANSFER REVIEW': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01579,
        "avg_price_move": 0.305,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Renewable Energy Credit Transfer Review
    },
    'PREFERRED STOCK ISSUANCE': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01566,
        "avg_price_move": -0.24,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Preferred Stock Issuance
    },
    'COMPANY BOARD ISSUES RESPONSE TO ACTIVIST': {
        "direction": "positive",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.01534,
        "avg_price_move": 0.337,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 2,
        # example: ByteLayer Board Issues Response to Activist
    },
    'PROJECT DELAYS RAISE MAC CONCERNS': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.015,
        "avg_price_move": 0.124,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Project Delays Raise MAC Concerns
    },
    'DOJ REQUESTS EXTENDED REVIEW': {
        "direction": "negative",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.01497,
        "avg_price_move": -0.18,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 3,
        # example: DOJ Requests Extended Review
    },
    'EXCHANGE RATIO COLLAR DISCUSSED': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01471,
        "avg_price_move": -0.483,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: Exchange Ratio Collar Discussed
    },
    'UK CMA PHASE I REVIEW COMPLETED': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01433,
        "avg_price_move": 0.098,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 6,
        # example: UK CMA Phase I Review Completed
    },
    'STATE BANKING REGULATORS PROVIDE CLEARANCE': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01416,
        "avg_price_move": 0.331,
        "confidence": 1.0,
        "n_obs": 14,
        "n_clean": 11,
        # example: State Banking Regulators Provide Clearance
    },
    'EARLY VOTE RESULTS SHOW STRONG SUPPORT': {
        "direction": "positive",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.01386,
        "avg_price_move": -0.148,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Early Vote Results Show Strong Support
    },
    'INDEX REBALANCING IMPLICATIONS': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.0138,
        "avg_price_move": -0.07,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 6,
        # example: Index Rebalancing Implications
    },
    'EXPECTED TIMELINE REVISED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01343,
        "avg_price_move": 0.491,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 7,
        # example: Expected Timeline Revised
    },
    'FEDERAL RESERVE ANNOUNCES RATE DECISION': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01278,
        "avg_price_move": 0.027,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Federal Reserve Announces Rate Decision
    },
    'COMPANY WAIVES MAC': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01275,
        "avg_price_move": -0.11,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: EastEnergy Waives MAC
    },
    'PROJECT FINANCE COMMITMENT SECURED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01269,
        "avg_price_move": 0.243,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 7,
        # example: Project Finance Commitment Secured
    },
    'BRIDGE LOAN REPLACED WITH TERM FACILITY': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01266,
        "avg_price_move": 0.329,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 7,
        # example: Bridge Loan Replaced with Term Facility
    },
    'FERC NOTIFICATION FILED': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01265,
        "avg_price_move": 0.26,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 8,
        # example: FERC Notification Filed
    },
    'RENEWABLE ENERGY SECTOR SELL-OFF': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01254,
        "avg_price_move": -0.023,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 6,
        # example: Renewable Energy Sector Sell-Off
    },
    'CHINESE SAMR EXTENDS REVIEW PERIOD': {
        "direction": "negative",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.01243,
        "avg_price_move": 0.045,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 6,
        # example: Chinese SAMR Extends Review Period
    },
    'ENVIRONMENTAL GROUPS EXPRESS SUPPORT': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0124,
        "avg_price_move": 0.22,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Environmental Groups Express Support
    },
    'FERC ISSUES ORDER APPROVING TRANSACTION': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01232,
        "avg_price_move": 0.245,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 5,
        # example: FERC Issues Order Approving Transaction
    },
    'CAPITAL PLAN APPROVED BY FED': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01227,
        "avg_price_move": -0.2,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 4,
        # example: Capital Plan Approved by Fed
    },
    'INTERCONNECTION RIGHTS CONFIRMED': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01196,
        "avg_price_move": -0.322,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 8,
        # example: Interconnection Rights Confirmed
    },
    'CONDITIONS CHECKLIST PUBLISHED': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01124,
        "avg_price_move": -0.293,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: Conditions Checklist Published
    },
    'CFIUS NATIONAL SECURITY REVIEW INITIATED': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.01097,
        "avg_price_move": 0.119,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: CFIUS National Security Review Initiated
    },
    'ASSET SALE PROCEEDS EXCEED TARGET': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01049,
        "avg_price_move": -0.197,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: Asset Sale Proceeds Exceed Target
    },
    'CREDIT MARKETS FLASH WARNING SIGNS AS SPREADS WIDEN': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01014,
        "avg_price_move": 0.396,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 7,
        # example: Credit Markets Flash Warning Signs as Spreads Widen
    },
    'STATE AG COALITION FILES LAWSUIT': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01,
        "avg_price_move": -0.264,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: State AG Coalition Files Lawsuit
    },
    'SHARE BUYBACK PROGRAM ANNOUNCED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00988,
        "avg_price_move": 0.387,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 2,
        # example: Share Buyback Program Announced
    },
    'CONVERTIBLE DEBT REFINANCED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00947,
        "avg_price_move": -0.099,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 10,
        # example: Convertible Debt Refinanced
    },
    'BANK SYNDICATE EXPANDS': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00905,
        "avg_price_move": 0.127,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 7,
        # example: Bank Syndicate Expands
    },
    'COMPANY SHAREHOLDER QUESTIONS DEAL LOGIC': {
        "direction": "negative",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.009,
        "avg_price_move": -0.113,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 7,
        # example: CloudSys Shareholder Questions Deal Logic
    },
    'ISS STRONGLY RECOMMENDS APPROVAL': {
        "direction": "negative",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00898,
        "avg_price_move": -0.457,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 7,
        # example: ISS Strongly Recommends Approval
    },
    'MAJOR TRANSACTION IN ADJACENT SECTOR COLLAPSES': {
        "direction": "positive",
        "severity": "small",
        "category": "PRC",
        "avg_dp": 0.00877,
        "avg_price_move": 0.03,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: Major Transaction in Adjacent Sector Collapses
    },
    'INVESTMENT GRADE RATING AFFIRMED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0085,
        "avg_price_move": 0.32,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: Investment Grade Rating Affirmed
    },
    'INTEGRATED UTILITY IDENTIFIED AS BIDDER': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00836,
        "avg_price_move": 0.085,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Integrated Utility Identified as Bidder
    },
    'SENIOR NOTES OFFERING SUCCESSFUL': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0082,
        "avg_price_move": 0.126,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: Senior Notes Offering Successful
    },
    'OIL PRICE COLLAPSE RAISES QUESTIONS': {
        "direction": "positive",
        "severity": "small",
        "category": "PRC",
        "avg_dp": 0.0081,
        "avg_price_move": 0.208,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: Oil Price Collapse Raises Questions
    },
    'STATE RENEWABLE ENERGY REVIEW': {
        "direction": "negative",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00748,
        "avg_price_move": 0.147,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: State Renewable Energy Review
    },
    'EPA ISSUES SUPPORTIVE STATEMENT': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00724,
        "avg_price_move": 0.126,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 2,
        # example: EPA Issues Supportive Statement
    },
    "MOODY'S PLACES RATINGS UNDER REVIEW": {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00705,
        "avg_price_move": 0.238,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Moody's Places Ratings Under Review
    },
    'HSR FILING MADE': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.0069,
        "avg_price_move": -0.256,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 7,
        # example: HSR Filing Made
    },
    'GLASS LEWIS RECOMMENDS APPROVAL': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00685,
        "avg_price_move": 0.183,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Glass Lewis Recommends Approval
    },
    'TAX CREDIT EXTENSION UNCERTAINTY': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00674,
        "avg_price_move": -0.104,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: Tax Credit Extension Uncertainty
    },
    'COMPANY WAIVES MAC CLAUSE': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00667,
        "avg_price_move": -0.14,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Pharmaco Waives MAC Clause
    },
    'MERGER AGREEMENT EXECUTED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00656,
        "avg_price_move": -0.041,
        "confidence": 1.0,
        "n_obs": 15,
        "n_clean": 9,
        # example: Merger Agreement Executed
    },
    'BREAKUP FEE STRUCTURE DETAILED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00617,
        "avg_price_move": 0.161,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 8,
        # example: Breakup Fee Structure Detailed
    },
    'CLASS ACTION FILED IN DELAWARE': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00617,
        "avg_price_move": -0.045,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: Class Action Filed in Delaware
    },
    'SECTOR MULTIPLE COMPRESSION': {
        "direction": "positive",
        "severity": "small",
        "category": "PRC",
        "avg_dp": 0.00613,
        "avg_price_move": -0.047,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: Sector Multiple Compression
    },
    'PROXY ADVISORY FIRM ISS RECOMMENDS APPROVAL': {
        "direction": "negative",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00595,
        "avg_price_move": -0.125,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Proxy Advisory Firm ISS Recommends Approval
    },
    'CONVERTIBLE NOTE HOLDERS SEEK CLARITY': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00594,
        "avg_price_move": 0.152,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: Convertible Note Holders Seek Clarity
    },
    'INTEGRATION TEAMS FORMED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00558,
        "avg_price_move": 0.122,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 4,
        # example: Integration Teams Formed
    },
    'COMPANY REPORTS STRONG QUARTERLY EARNINGS': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00554,
        "avg_price_move": 0.115,
        "confidence": 1.0,
        "n_obs": 11,
        "n_clean": 7,
        # example: Pharmaco Reports Strong Quarterly Earnings
    },
    'SHAREHOLDER LITIGATION FILED': {
        "direction": "negative",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00551,
        "avg_price_move": -0.099,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Shareholder Litigation Filed
    },
    'UNSOLICITED INQUIRY RECEIVED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00551,
        "avg_price_move": -0.112,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 6,
        # example: Unsolicited Inquiry Received
    },
    'REGULATORY FILINGS SUBMITTED': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00543,
        "avg_price_move": -0.056,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 8,
        # example: Regulatory Filings Submitted
    },
    'COMPANY SHAREHOLDER BACKLASH': {
        "direction": "negative",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00532,
        "avg_price_move": -0.112,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Pharmaco Shareholder Backlash
    },
    'ENERGY SECTOR CREDIT SPREAD WIDENING': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00529,
        "avg_price_move": 0.2,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Energy Sector Credit Spread Widening
    },
    'BOND MARKET VOLATILITY CONCERNS': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00524,
        "avg_price_move": 0.11,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Bond Market Volatility Concerns
    },
    'RUMOR OF COMPETING INTEREST': {
        "direction": "negative",
        "severity": "small",
        "category": "ALT",
        "avg_dp": -0.00524,
        "avg_price_move": -0.11,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Rumor of Competing Interest
    },
    'STRATEGIC INVESTOR TAKES STAKE': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00523,
        "avg_price_move": -0.016,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 7,
        # example: Strategic Investor Takes Stake
    },
    'BREACH OF TRANSACTION COVENANT ALLEGED': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00521,
        "avg_price_move": -0.085,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: Breach of Transaction Covenant Alleged
    },
    'PRELIMINARY VOTE COUNT SHOWS STRONG SUPPORT': {
        "direction": "negative",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00521,
        "avg_price_move": -0.315,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Preliminary Vote Count Shows Strong Support
    },
    'QUARTERLY INSTITUTIONAL PORTFOLIO REBALANCING UNDERWAY': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00519,
        "avg_price_move": 0.007,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 9,
        # example: Quarterly Institutional Portfolio Rebalancing Underway
    },
    'COMPANY SHAREHOLDER QUESTIONS': {
        "direction": "negative",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00509,
        "avg_price_move": 0.202,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: EastEnergy Shareholder Questions
    },
    'INTEGRATION PLANNING UNDERWAY': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00501,
        "avg_price_move": -0.02,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 5,
        # example: Integration Planning Underway
    },
    'INTEGRATION PLANNING COMMENCES': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00492,
        "avg_price_move": -0.221,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 6,
        # example: Integration Planning Commences
    },
    'CLOSING CONDITIONS STATUS UPDATE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0049,
        "avg_price_move": 0.046,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 7,
        # example: Closing Conditions Status Update
    },
    'TLAC REQUIREMENTS CLARIFIED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00475,
        "avg_price_move": 0.117,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: TLAC Requirements Clarified
    },
    'COMPANY MANAGEMENT PROVIDES UPDATED MARKET OUTLOOK': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0046,
        "avg_price_move": -0.046,
        "confidence": 1.0,
        "n_obs": 34,
        "n_clean": 29,
        # example: CloudSys Management Provides Updated Market Outlook
    },
    'ANTITRUST EXPERTS RAISE COMPETITION CONCERNS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00452,
        "avg_price_move": 0.114,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Antitrust Experts Raise Competition Concerns
    },
    'INTEGRATION TEAMS APPOINTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00439,
        "avg_price_move": -0.071,
        "confidence": 1.0,
        "n_obs": 14,
        "n_clean": 10,
        # example: Integration Teams Appointed
    },
    'CONSUMER ADVOCACY GROUPS FILE OPPOSITION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00431,
        "avg_price_move": 0.304,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 7,
        # example: Consumer Advocacy Groups File Opposition
    },
    'COMPANIES COMMIT TO RENEWABLE INVESTMENT': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00426,
        "avg_price_move": -0.12,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: Companies Commit to Renewable Investment
    },
    'ASSET QUALITY DETERIORATION NOTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00424,
        "avg_price_move": 0.065,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Asset Quality Deterioration Noted
    },
    'FED ANNOUNCES ENHANCED REVIEW PROCESS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00424,
        "avg_price_move": -0.065,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: Fed Announces Enhanced Review Process
    },
    'FTC REQUESTS ADDITIONAL INFORMATION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.0042,
        "avg_price_move": -0.042,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 7,
        # example: FTC Requests Additional Information
    },
    'EMPLOYEE RETENTION PACKAGES OFFERED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00411,
        "avg_price_move": -0.08,
        "confidence": 1.0,
        "n_obs": 13,
        "n_clean": 10,
        # example: Employee Retention Packages Offered
    },
    'DIVIDEND POLICY MAINTAINED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00408,
        "avg_price_move": 0.062,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: Dividend Policy Maintained
    },
    'CREDIT RATING DOWNGRADE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00401,
        "avg_price_move": -0.084,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: Credit Rating Downgrade
    },
    'CONGRESSIONAL TECH OVERSIGHT HEARING': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00385,
        "avg_price_move": -0.027,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 7,
        # example: Congressional Tech Oversight Hearing
    },
    'LEGAL CHALLENGE DISMISSED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00381,
        "avg_price_move": 0.075,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Legal Challenge Dismissed
    },
    'INVESTMENT BANKING ACTIVITY ACCELERATES ACROSS SECTORS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00367,
        "avg_price_move": -0.107,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Investment Banking Activity Accelerates Across Sectors
    },
    'COMPANY SHAREHOLDER MEETING SCHEDULED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00365,
        "avg_price_move": -0.077,
        "confidence": 1.0,
        "n_obs": 15,
        "n_clean": 11,
        # example: Targenix Shareholder Meeting Scheduled
    },
    'CREDIT ANALYSTS REVIEW COMPANY DEBT PROFILE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00363,
        "avg_price_move": 0.31,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 6,
        # example: Credit Analysts Review CloudSys Debt Profile
    },
    'TERMINATION FEE STRUCTURE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00355,
        "avg_price_move": 0.058,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 9,
        # example: Termination Fee Structure
    },
    'PIPELINE SAFETY REVIEW ANNOUNCED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00354,
        "avg_price_move": -0.402,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: Pipeline Safety Review Announced
    },
    'FERC GRANTS EXPEDITED APPROVAL': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00334,
        "avg_price_move": -0.123,
        "confidence": 1.0,
        "n_obs": 14,
        "n_clean": 11,
        # example: FERC Grants Expedited Approval
    },
    'REGULATORY TIMELINE SLIPPAGE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00334,
        "avg_price_move": -0.049,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 7,
        # example: Regulatory Timeline Slippage
    },
    'PROXY ADVISORY FIRMS ISSUE DIVIDED RECOMMENDATIONS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00326,
        "avg_price_move": -0.05,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Proxy Advisory Firms Issue Divided Recommendations
    },
    'TICKER RECEIVES UNSOLICITED INQUIRY': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00317,
        "avg_price_move": -0.067,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 2,
        # example: TGX Receives Unsolicited Inquiry
    },
    'FEDERAL TAX CREDIT CLARIFICATION SOUGHT': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00312,
        "avg_price_move": 0.333,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: Federal Tax Credit Clarification Sought
    },
    'CLOSED-DOOR MEETING BETWEEN TRANSACTION PRINCIPALS REPORTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00308,
        "avg_price_move": -0.036,
        "confidence": 1.0,
        "n_obs": 30,
        "n_clean": 19,
        # example: Closed-Door Meeting Between Transaction Principals Reported
    },
    'STRONG PROJECT PIPELINE ANNOUNCED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00305,
        "avg_price_move": -0.186,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 6,
        # example: Strong Project Pipeline Announced
    },
    'ACTIVIST HEDGE FUND OPPOSES DEAL': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.00305,
        "avg_price_move": 0.064,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Activist Hedge Fund Opposes Deal
    },
    'FERC FILING FOR RENEWABLE MERGER': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00301,
        "avg_price_move": 0.356,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 3,
        # example: FERC Filing for Renewable Merger
    },
    'REGULATORY APPLICATIONS FILED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00294,
        "avg_price_move": 0.045,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 8,
        # example: Regulatory Applications Filed
    },
    'CREDIT FACILITY AMENDMENT NEGOTIATED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00287,
        "avg_price_move": -0.059,
        "confidence": 1.0,
        "n_obs": 13,
        "n_clean": 11,
        # example: Credit Facility Amendment Negotiated
    },
    'DEFINITIVE AGREEMENT ANNOUNCED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00286,
        "avg_price_move": -0.067,
        "confidence": 1.0,
        "n_obs": 13,
        "n_clean": 10,
        # example: Definitive Agreement Announced
    },
    'INDUSTRY CONFERENCE GENERATES TRANSACTION SPECULATION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00282,
        "avg_price_move": -0.097,
        "confidence": 1.0,
        "n_obs": 49,
        "n_clean": 36,
        # example: Industry Conference Generates Transaction Speculation
    },
    'CREDIT RATING AGENCIES PLACE TICKER ON WATCH': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00281,
        "avg_price_move": -0.059,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 5,
        # example: Credit Rating Agencies Place PHR on Watch
    },
    'BANKS PROPOSE ENHANCED CRA PLAN': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00274,
        "avg_price_move": 0.042,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 5,
        # example: Banks Propose Enhanced CRA Plan
    },
    'COMMUNITY GROUPS RAISE CRA CONCERNS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00264,
        "avg_price_move": -0.04,
        "confidence": 1.0,
        "n_obs": 13,
        "n_clean": 11,
        # example: Community Groups Raise CRA Concerns
    },
    'COMMODITY PRICE HEDGE PROGRAM': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "PRC",
        "avg_dp": -0.0024,
        "avg_price_move": -0.088,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Commodity Price Hedge Program
    },
    'COMPANY BOARD UNANIMOUSLY REAFFIRMS SUPPORT': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00238,
        "avg_price_move": -0.05,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Targenix Board Unanimously Reaffirms Support
    },
    'CENTRAL BANK ANNOUNCES ENHANCED LIQUIDITY FACILITIES': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00232,
        "avg_price_move": -0.246,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 5,
        # example: Central Bank Announces Enhanced Liquidity Facilities
    },
    'ASSET SALES TO FUND TRANSACTION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.0023,
        "avg_price_move": -0.052,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 8,
        # example: Asset Sales to Fund Transaction
    },
    'ESG-FOCUSED FUND OPPOSES TERMS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0023,
        "avg_price_move": 0.102,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 7,
        # example: ESG-Focused Fund Opposes Terms
    },
    'ISO-NE ISSUES FAVORABLE OPINION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.0023,
        "avg_price_move": 0.053,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: ISO-NE Issues Favorable Opinion
    },
    'MATERIAL ADVERSE CHANGE CLAUSE CONCERN': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00224,
        "avg_price_move": -0.047,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 7,
        # example: Material Adverse Change Clause Concern
    },
    'BOARD RELEASES DETAILED FAIRNESS ANALYSIS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.00217,
        "avg_price_move": 0.07,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 7,
        # example: Board Releases Detailed Fairness Analysis
    },
    'INFRASTRUCTURE MODERNIZATION REQUIREMENTS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00215,
        "avg_price_move": 0.051,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: Infrastructure Modernization Requirements
    },
    'BONDHOLDER LITIGATION FILED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00207,
        "avg_price_move": 0.052,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Bondholder Litigation Filed
    },
    'HART-SCOTT-RODINO FILING SUBMITTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00193,
        "avg_price_move": -0.055,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Hart-Scott-Rodino Filing Submitted
    },
    'NON-BINDING INDICATION RECEIVED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00181,
        "avg_price_move": -0.09,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: Non-Binding Indication Received
    },
    'COMPANY SETS MEETING FOR SHAREHOLDER VOTE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.00181,
        "avg_price_move": 0.028,
        "confidence": 1.0,
        "n_obs": 11,
        "n_clean": 9,
        # example: FinSure Sets Meeting for Shareholder Vote
    },
    'MATERIAL ADVERSE EFFECT QUESTION RAISED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00181,
        "avg_price_move": 0.033,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: Material Adverse Effect Question Raised
    },
    'REVERSE TERMINATION FEE INCREASED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00175,
        "avg_price_move": 0.037,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 6,
        # example: Reverse Termination Fee Increased
    },
    'SELL-SIDE ANALYSTS ISSUE DIVERGENT VALUATION ASSESSMENTS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00173,
        "avg_price_move": 0.108,
        "confidence": 1.0,
        "n_obs": 42,
        "n_clean": 27,
        # example: Sell-Side Analysts Issue Divergent Valuation Assessments
    },
    'FERC STAFF HOLDS TECHNICAL WORKING SESSION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.0017,
        "avg_price_move": 0.068,
        "confidence": 1.0,
        "n_obs": 16,
        "n_clean": 10,
        # example: FERC Staff Holds Technical Working Session
    },
    'IMPROVED FINANCIAL DISCLOSURES': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00168,
        "avg_price_move": 0.217,
        "confidence": 1.0,
        "n_obs": 16,
        "n_clean": 11,
        # example: Improved Financial Disclosures
    },
    'COMPANY INVESTOR RELATIONS CONCERNS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00162,
        "avg_price_move": -0.034,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 3,
        # example: PetroNorth Investor Relations Concerns
    },
    'OUTSIDE DATE EXTENDED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00161,
        "avg_price_move": -0.067,
        "confidence": 1.0,
        "n_obs": 29,
        "n_clean": 22,
        # example: Outside Date Extended
    },
    'GROWING MARKET SPECULATION SURROUNDS DEAL VIABILITY': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00152,
        "avg_price_move": 0.126,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Growing Market Speculation Surrounds Deal Viability
    },
    'CONFIDENTIAL APPROACH DISCLOSED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00151,
        "avg_price_move": -0.005,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: Confidential Approach Disclosed
    },
    'COMPANY STOCK PRICE DECLINE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "PRC",
        "avg_dp": -0.0015,
        "avg_price_move": -0.031,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Pharmaco Stock Price Decline
    },
    'FTC STAFF HOLDS TECHNICAL WORKING SESSION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00146,
        "avg_price_move": -0.057,
        "confidence": 1.0,
        "n_obs": 22,
        "n_clean": 15,
        # example: FTC Staff Holds Technical Working Session
    },
    'KEY ENGINEER RETENTION PLAN ANNOUNCED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00132,
        "avg_price_move": 0.179,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 7,
        # example: Key Engineer Retention Plan Announced
    },
    'FDIC EXTENDS COMMENT PERIOD': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00131,
        "avg_price_move": -0.02,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: FDIC Extends Comment Period
    },
    'COMPANY REPORTS STRONG REVENUE GROWTH': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00129,
        "avg_price_move": -0.19,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: CloudSys Reports Strong Revenue Growth
    },
    'INSTITUTIONAL INVESTORS SIGNAL SUPPORT': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00129,
        "avg_price_move": 0.163,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: Institutional Investors Signal Support
    },
    'DIVIDEND SUSPENSION ANNOUNCED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00124,
        "avg_price_move": 0.03,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 8,
        # example: Dividend Suspension Announced
    },
    'BANK CREDIT SPREADS WIDEN SHARPLY': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00123,
        "avg_price_move": 0.019,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 5,
        # example: Bank Credit Spreads Widen Sharply
    },
    'THIRD-PARTY REGULATORY ANALYSIS PUBLISHED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00113,
        "avg_price_move": -0.065,
        "confidence": 1.0,
        "n_obs": 31,
        "n_clean": 17,
        # example: Third-Party Regulatory Analysis Published
    },
    'DEBT FINANCING COMMITMENTS SECURED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00113,
        "avg_price_move": 0.038,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 5,
        # example: Debt Financing Commitments Secured
    },
    'DEFINITIVE AGREEMENT EXECUTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00113,
        "avg_price_move": -0.048,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 10,
        # example: Definitive Agreement Executed
    },
    'TRANSMISSION ACCESS QUESTIONS RAISED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00099,
        "avg_price_move": 0.205,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 4,
        # example: Transmission Access Questions Raised
    },
    'UNUSUAL INSTITUTIONAL TRADING ACTIVITY OBSERVED IN TICKER': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00096,
        "avg_price_move": -0.05,
        "confidence": 1.0,
        "n_obs": 37,
        "n_clean": 30,
        # example: Unusual Institutional Trading Activity Observed in SPK
    },
    'INTEGRATION PLANNING PROGRESSES': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00096,
        "avg_price_move": -0.023,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Integration Planning Progresses
    },
    'COMPANY SCHEDULES SHAREHOLDER MEETING': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00092,
        "avg_price_move": -0.066,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: SolarPeak Schedules Shareholder Meeting
    },
    'DEBT FINANCING FULLY COMMITTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00092,
        "avg_price_move": 0.023,
        "confidence": 1.0,
        "n_obs": 13,
        "n_clean": 9,
        # example: Debt Financing Fully Committed
    },
    'PRIVATE EQUITY INTEREST REPORTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.0009,
        "avg_price_move": -0.04,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 2,
        # example: Private Equity Interest Reported
    },
    'COMPANY SCHEDULES SHAREHOLDER VOTE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00087,
        "avg_price_move": -0.021,
        "confidence": 1.0,
        "n_obs": 10,
        "n_clean": 8,
        # example: GreenGrid Schedules Shareholder Vote
    },
    'FDIC ISSUES CONDITIONAL APPROVAL': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00087,
        "avg_price_move": 0.013,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: FDIC Issues Conditional Approval
    },
    'COUNSEL PROVIDES UPDATED RISK FACTOR DISCLOSURE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00086,
        "avg_price_move": 0.002,
        "confidence": 1.0,
        "n_obs": 46,
        "n_clean": 41,
        # example: Counsel Provides Updated Risk Factor Disclosure
    },
    'INTEREST RATE HEDGE EXECUTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00082,
        "avg_price_move": -0.017,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 3,
        # example: Interest Rate Hedge Executed
    },
    'COMPANY BOARD DEFENDS TRANSACTION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.00082,
        "avg_price_move": 0.012,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 3,
        # example: FinSure Board Defends Transaction
    },
    'ACTIVIST FUND BUILDS COMPANY STAKE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": -0.00082,
        "avg_price_move": 0.071,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 5,
        # example: Activist Fund Builds ByteLayer Stake
    },
    'COMPANY SETS SHAREHOLDER MEETING DATE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "SHR",
        "avg_dp": 0.00074,
        "avg_price_move": 0.09,
        "confidence": 1.0,
        "n_obs": 11,
        "n_clean": 7,
        # example: ByteLayer Sets Shareholder Meeting Date
    },
    'DOJ ANTITRUST DIVISION SIGNALS STRICTER MERGER ENFORCEMENT': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00073,
        "avg_price_move": -0.097,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 4,
        # example: DOJ Antitrust Division Signals Stricter Merger Enforcement
    },
    'SUPPLEMENTAL ENVIRONMENTAL REVIEW': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00071,
        "avg_price_move": -0.029,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 3,
        # example: Supplemental Environmental Review
    },
    'SUCCESSFUL BOND OFFERING': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00062,
        "avg_price_move": -0.025,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Successful Bond Offering
    },
    'STRATEGIC INVESTOR SHOWS INTEREST': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00056,
        "avg_price_move": 0.05,
        "confidence": 1.0,
        "n_obs": 2,
        "n_clean": 2,
        # example: Strategic Investor Shows Interest
    },
    'COMPANY ENGAGES ADVISORS FOR STRATEGIC REVIEW': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00054,
        "avg_price_move": -0.046,
        "confidence": 1.0,
        "n_obs": 25,
        "n_clean": 15,
        # example: GreenGrid Engages Advisors for Strategic Review
    },
    'EQUITY RESEARCH DOWNGRADES COMPANY': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00053,
        "avg_price_move": 0.067,
        "confidence": 1.0,
        "n_obs": 7,
        "n_clean": 4,
        # example: Equity Research Downgrades CloudSys
    },
    'DEPOSIT OUTFLOWS ACCELERATE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00052,
        "avg_price_move": -0.008,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 3,
        # example: Deposit Outflows Accelerate
    },
    'FEDERAL RESERVE STAFF HOLDS TECHNICAL WORKING SESSION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00047,
        "avg_price_move": 0.007,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 7,
        # example: Federal Reserve Staff Holds Technical Working Session
    },
    'COMPANY SHARE PRICE VOLATILITY': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "PRC",
        "avg_dp": -0.00044,
        "avg_price_move": 0.008,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 2,
        # example: EastEnergy Share Price Volatility
    },
    'FERC COMMISSIONER COMMENDS TRANSACTION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.00042,
        "avg_price_move": -0.087,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: FERC Commissioner Commends Transaction
    },
    'MERGER AGREEMENT SIGNED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00042,
        "avg_price_move": -0.009,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 6,
        # example: Merger Agreement Signed
    },
    'REVERSE TERMINATION FEE TRIGGERED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00042,
        "avg_price_move": 0.003,
        "confidence": 1.0,
        "n_obs": 3,
        "n_clean": 3,
        # example: Reverse Termination Fee Triggered
    },
    'FTC OPENS PRELIMINARY REVIEW OF TECH MERGER': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.0004,
        "avg_price_move": 0.112,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 5,
        # example: FTC Opens Preliminary Review of Tech Merger
    },
    'STRONG QUARTERLY RESULTS REPORTED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00029,
        "avg_price_move": -0.004,
        "confidence": 1.0,
        "n_obs": 9,
        "n_clean": 5,
        # example: Strong Quarterly Results Reported
    },
    'CANADIAN REGULATORS PROVIDE CLEARANCE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00028,
        "avg_price_move": -0.21,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 3,
        # example: Canadian Regulators Provide Clearance
    },
    'EARNINGS SHORTFALL RAISES MAC QUESTIONS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00026,
        "avg_price_move": -0.028,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 4,
        # example: Earnings Shortfall Raises MAC Questions
    },
    'STANDSTILL AGREEMENT BREACHED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00024,
        "avg_price_move": -0.003,
        "confidence": 1.0,
        "n_obs": 4,
        "n_clean": 4,
        # example: Standstill Agreement Breached
    },
    'MERGER AGREEMENT SIGNED AND ANNOUNCED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00021,
        "avg_price_move": -0.178,
        "confidence": 1.0,
        "n_obs": 15,
        "n_clean": 12,
        # example: Merger Agreement Signed and Announced
    },
    'EQUITY CO-INVESTMENT SECURED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00018,
        "avg_price_move": -0.03,
        "confidence": 1.0,
        "n_obs": 12,
        "n_clean": 8,
        # example: Equity Co-Investment Secured
    },
    'INFRASTRUCTURE FUND OPPOSES TERMS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00012,
        "avg_price_move": -0.02,
        "confidence": 1.0,
        "n_obs": 6,
        "n_clean": 5,
        # example: Infrastructure Fund Opposes Terms
    },
    'EXECUTIVE ORDER TARGETS COMPETITION POLICY ACROSS INDUSTRIES': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 9e-05,
        "avg_price_move": 0.004,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 8,
        # example: Executive Order Targets Competition Policy Across Industries
    },
    'STOCK MARKET VOLATILITY AFFECTS EXCHANGE RATIO': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 6e-05,
        "avg_price_move": -0.054,
        "confidence": 1.0,
        "n_obs": 11,
        "n_clean": 7,
        # example: Stock Market Volatility Affects Exchange Ratio
    },
    'KEY EMPLOYEE RETENTION AGREEMENTS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -6e-05,
        "avg_price_move": -0.001,
        "confidence": 1.0,
        "n_obs": 8,
        "n_clean": 5,
        # example: Key Employee Retention Agreements
    },
    'TECH INDUSTRY COALITION OPPOSES DEAL': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 5e-05,
        "avg_price_move": -0.04,
        "confidence": 1.0,
        "n_obs": 5,
        "n_clean": 4,
        # example: Tech Industry Coalition Opposes Deal
    },
    'INDEPENDENT FAIRNESS REVIEW GENERATES BOARD DISCUSSION': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "REG",
        "avg_dp": -5e-05,
        "avg_price_move": 0.073,
        "confidence": 1.0,
        "n_obs": 21,
        "n_clean": 17,
        # example: Independent Fairness Review Generates Board Discussion
    },
    'ESCALATING GEOPOLITICAL TENSIONS RATTLE GLOBAL MARKETS': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00978,
        "avg_price_move": -0.072,
        "confidence": 0.83,
        "n_obs": 4,
        "n_clean": 1,
        # example: Escalating Geopolitical Tensions Rattle Global Markets
    },
    'REGULATORY TIMELINE EXTENDED': {
        "direction": "negative",
        "severity": "medium",
        "category": "REG",
        "avg_dp": -0.02462,
        "avg_price_move": -0.333,
        "confidence": 0.67,
        "n_obs": 3,
        "n_clean": 1,
        # example: Regulatory Timeline Extended
    },
    'COMPANIES COMMIT TO CAPACITY EXPANSION': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00819,
        "avg_price_move": 0.033,
        "confidence": 0.67,
        "n_obs": 3,
        "n_clean": 1,
        # example: Companies Commit to Capacity Expansion
    },
    'DOJ PROVIDES CONDITIONAL CLEARANCE': {
        "direction": "negative",
        "severity": "small",
        "category": "REG",
        "avg_dp": -0.0198,
        "avg_price_move": -0.165,
        "confidence": 0.5,
        "n_obs": 2,
        "n_clean": 1,
        # example: DOJ Provides Conditional Clearance
    },
    'STOCK PRICE CONDITIONS SATISFIED': {
        "direction": "negative",
        "severity": "small",
        "category": "PRC",
        "avg_dp": -0.00573,
        "avg_price_move": 0.02,
        "confidence": 0.5,
        "n_obs": 2,
        "n_clean": 1,
        # example: Stock Price Conditions Satisfied
    },
    'BRIDGE FINANCING COMMITMENT SIGNED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00218,
        "avg_price_move": -0.05,
        "confidence": 0.5,
        "n_obs": 2,
        "n_clean": 1,
        # example: Bridge Financing Commitment Signed
    },
    'FINANCING CONDITION SATISFIED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00214,
        "avg_price_move": 0.045,
        "confidence": 0.5,
        "n_obs": 2,
        "n_clean": 1,
        # example: Financing Condition Satisfied
    },
    'FORCE MAJEURE EVENT RAISES TRANSACTION CONCERNS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00197,
        "avg_price_move": 0.045,
        "confidence": 0.5,
        "n_obs": 2,
        "n_clean": 1,
        # example: Force Majeure Event Raises Transaction Concerns
    },
    'COMPANY SWEETENS OFFER TERMS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00158,
        "avg_price_move": -0.03,
        "confidence": 0.5,
        "n_obs": 2,
        "n_clean": 1,
        # example: PetroNorth Sweetens Offer Terms
    },
    'COMPANY INCREASES OFFER PRICE': {
        "direction": "positive",
        "severity": "large",
        "category": "PRC",
        "avg_dp": 0.16055,
        "avg_price_move": 2.46,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Atlas Bank Increases Offer Price
    },
    'FTC COMMISSIONER DISSENT PUBLISHED': {
        "direction": "negative",
        "severity": "large",
        "category": "REG",
        "avg_dp": -0.1303,
        "avg_price_move": -3.52,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: FTC Commissioner Dissent Published
    },
    'STRONG EARLY VOTING RESULTS': {
        "direction": "negative",
        "severity": "large",
        "category": "FIN",
        "avg_dp": -0.08484,
        "avg_price_move": -1.3,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Strong Early Voting Results
    },
    'VOTE OUTCOME APPEARS FAVORABLE': {
        "direction": "positive",
        "severity": "medium",
        "category": "SHR",
        "avg_dp": 0.03276,
        "avg_price_move": 0.22,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Vote Outcome Appears Favorable
    },
    'DOJ ANTITRUST DIVISION SIGNALS CONCERNS': {
        "direction": "negative",
        "severity": "medium",
        "category": "REG",
        "avg_dp": -0.02881,
        "avg_price_move": -0.74,
        "confidence": 0.33,
        "n_obs": 2,
        "n_clean": 0,
        # example: DOJ Antitrust Division Signals Concerns
    },
    'UTILITY SUBMITS FORMAL PROPOSAL': {
        "direction": "negative",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.01236,
        "avg_price_move": -0.07,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Utility Submits Formal Proposal
    },
    'FEDERAL JUDGE DENIES STATE AG INJUNCTION': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.01086,
        "avg_price_move": 0.32,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Federal Judge Denies State AG Injunction
    },
    'STATE COMMISSION ACCEPTS COMMITMENTS': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00797,
        "avg_price_move": -0.305,
        "confidence": 0.33,
        "n_obs": 2,
        "n_clean": 0,
        # example: State Commission Accepts Commitments
    },
    'STATE COMMISSION ACCEPTS MITIGATION PLAN': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.00599,
        "avg_price_move": 0.14,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: State Commission Accepts Mitigation Plan
    },
    'FEDERAL RESERVE APPROVES TRANSACTION': {
        "direction": "positive",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00571,
        "avg_price_move": 0.12,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Federal Reserve Approves Transaction
    },
    'COMPETING BIDDER IDENTIFIED AS NOVAPHARMA': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "ALT",
        "avg_dp": 0.00469,
        "avg_price_move": -1.2,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Competing Bidder Identified as NovaPharma
    },
    'ALL FINANCING CONDITIONS MET': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00243,
        "avg_price_move": -0.05,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: All Financing Conditions Met
    },
    'COMPANY WAIVES MAC CONCERNS': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": -0.00147,
        "avg_price_move": -0.09,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: PetroNorth Waives MAC Concerns
    },
    'ALTERNATIVE BIDDER IDENTIFIED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "ALT",
        "avg_dp": 0.00137,
        "avg_price_move": -1.05,
        "confidence": 0.33,
        "n_obs": 1,
        "n_clean": 1,
        # example: Alternative Bidder Identified
    },
    'REPORTS SUGGEST FINAL REGULATORY HURDLES NEARING RESOLUTION': {
        "direction": "positive",
        "severity": "small",
        "category": "REG",
        "avg_dp": 0.0075,
        "avg_price_move": -0.34,
        "confidence": 0.17,
        "n_obs": 1,
        "n_clean": 0,
        # example: Reports Suggest Final Regulatory Hurdles Nearing Resolution
    },
    'MARKET CAP CONCERNS EMERGE': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.00429,
        "avg_price_move": 0.21,
        "confidence": 0.17,
        "n_obs": 1,
        "n_clean": 0,
        # example: Market Cap Concerns Emerge
    },
    'MATERIAL BREACH OF MERGER COVENANT ALLEGED': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0,
        "avg_price_move": 0.0,
        "confidence": 0.17,
        "n_obs": 1,
        "n_clean": 0,
        # example: Material Breach of Merger Covenant Alleged
    },
    'WELCOME TO THE RITC 2026 MERGER ARBITRAGE CASE - PRACTICE SERVER': {
        "direction": "ambiguous",
        "severity": "small",
        "category": "FIN",
        "avg_dp": 0.0,
        "avg_price_move": 0.0,
        "confidence": 0.17,
        "n_obs": 1,
        "n_clean": 0,
        # example: Welcome to the RITC 2026 Merger Arbitrage Case - practice se
    },
}


ALL_TICKERS = ["TGX", "PHR", "BYL", "CLD", "GGD", "PNR", "FSR", "ATB", "SPK", "EEC"]
ALL_COMPANY_NAMES = [
    "TARGENIX", "PHARMACO", "BYTELAYER", "CLOUDSYS", "GREENGRID",
    "PETRONORTH", "FINSURE", "ATLAS BANK", "ATLAS", "SOLARPEAK",
    "EASTENERGY", "EAST ENERGY",
]


def normalize_headline(headline: str) -> str:
    text = headline.upper().strip()
    for ticker in ALL_TICKERS:
        text = text.replace(ticker, "TICKER")
    for name in ALL_COMPANY_NAMES:
        text = text.replace(name, "COMPANY")
    text = " ".join(text.split())
    return text


def lookup_news(headline: str) -> dict | None:
    """Look up a headline in the master table. Returns classification or None."""
    normalized = normalize_headline(headline)

    # Exact match
    if normalized in MASTER_LOOKUP:
        return MASTER_LOOKUP[normalized]

    # Substring match (template in headline or headline in template)
    for template, classification in MASTER_LOOKUP.items():
        if template in normalized or normalized in template:
            return classification

    return None
